algoritmo " Enquanto - Letra for diferente de A"
// Função :
// Autor : Isabela
// Data : 09/07/2024
// Seção de Declarações 
var

   letra : caractere

inicio

      Enquanto letra <> "a" faca
      
               Escreval ("Digite uma letra")
               leia(letra)
               
      FimEnquanto
      
               Escreval("Parabéns, você digitou a letra A!!!!")
               
               
               
               
               

fimalgoritmo
