algoritmo "Enquanto - Intervalo 0 a 10"
// Função :
// Autor :
// Data : 10/07/2024
// Seção de Declarações 
var

   numero : inteiro

inicio

      Escreval("Digite um número no intervalo de 1 a 10.")
      leia(numero)


      Enquanto ( numero < 0 ) ou ( numero > 10 ) Faca
      
               Escreval("Digite um número no intervalo de 1 a 10.")
               leia(numero)
      
      FimEnquanto

      Escreval("Parabéns!!")
      

fimalgoritmo
