algoritmo "Intervalo de 2 a 10"
// Função :
// Autor : Isabela
// Data : 08/07/2024
// Seção de Declarações 
var

   numero: inteiro

inicio

      Escreval("Digite um número.")
      leia(numero)
      
      Se ( numero >= 2 ) e ( numero <= 10 ) Entao
      
           Escreval( "O ", numero, " está no intervalo de 2 a 10")
      
      Senao
      
           Escreval ("O ", numero, " não está no intervalo de 2 a 10")
      
      FimSe

fimalgoritmo
