algoritmo "Par e ímpar"
// Função :
// Autor :  Isabela
// Data : 08/07/2024
// Seção de Declarações 
var

   numero : inteiro

inicio

    Escreval("Digite um número INTEIRO.")
    leia(numero)
    
    Se ( numero mod 2 = 0 ) Entao
    
         Escreval("O número ", numero," é PAR!")
    
    Senao
    
         Escreval("O número ", numero," é ÍMPAR!")
         
         FimSe

fimalgoritmo
